### PR TITLE
create BinaryArray directly from byte slice

### PR DESCRIPTION
**Pull request by nevi-me**
This prevents converting to `String` > `&str` > `&[u8]`

### CODE REVIEW

**Comment by nevi-me** [comment]
Hi @ntrinquier, this (potentially) addresses the TODO that existed in DataFusion for limit and filter. I thought that maybe it's good to take care of it now rather than later. 

I thought of also adding filters for `ListArray` and StructArray`, but I can open a JIRA and address that separately/later. Let me know if you're happy to add this to your PR on apache/arrow.

**Comment by ntrinquier** [comment]
@nevi-me Happy to look into the TODO.

I'll try to add `ListArray` and `StructArray` if this is not too much work (otherwise we can address that in a separate task).

**Comment by nevi-me** [comment]
We might have date/time arrays soon, so we could address list and Struct along with date/time

**Comment by ntrinquier** [comment]
:ok_hand:

**Pull request merged**
